### ISSUE TITLE
Avoid using multiple sxhkd instances 

### ISSUE THREAD

**Issue by siduck76** [Theory-of-Everything/voidbook-dotfiles#1]
sxhkd should be used only once! in your bspwmrc file replace sxhkd & with   pgrep -x sxhkd > /dev/null || sxhkd &    

https://github.com/Theory-of-Everything/voidbook-dotfiles/blob/master/bspwm/bspwmrc#L3

 . It kills all existing sxhkd instances and opens only one sxhkd instance.

**Comment by Theory-of-Everything** [comment]
Thanks for pointing that out! Still learning my way around the shell, so I don't have the greatest understanding of everything just yet, but I'll fix it with the next upcoming commit.
